debug: false  # debug ?? -> ?? ??
management: # actuator endpoint? ??? ??? ?? ???? ??
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    kr.co.fastcampus.board : debug
    org.springframework.web.servlet : debug #?? request, response? debug
    org.hibernate.type.descriptor.sql.BasicBinder : trace
spring:
  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
    url : jdbc:mysql://localhost:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
    username : jsh
    password : qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true #???? ?????? ??
    hibernate:
      ddl-auto: create  #entity? ?? ???? table? ??
    open-in-view: false
    show-sql: true  # ?? ??????
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  #  h2:
#    console:
#      enabled: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf:
    cache: false
  thymeleaf3:
    decoupled-logic: true
#  data.rest:
#  data:
#    rest:
#      base-path: /api
#      detection-strategy: annotated

---
#
#spring:
#  config:
#    activate:
#      on-profile: testDB
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none
